import React from 'react';
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};


const Aboutpage = () => {
    return (
        <div>
            <h1>About Us</h1>
        </div>
    );
};

export default Aboutpage;