import React from 'react';
export const metadata = {
  title: "Career",
  description: "Generated by create next app",
};

const CareerPage = () => {
    return (
        <div>
            <h1>Career Opportunities</h1>
        </div>
    );
};

export default CareerPage;